CREATE TABLE aire.RefererServidores (
    IdRefererServidores NUMBER GENERATED BY DEFAULT AS IDENTITY,
    RequestHeadersReferer NVARCHAR2(1000) NOT NULL,
    PermitirAcceso CHAR(1) CHECK (PermitirAcceso IN ('0', '1')) NOT NULL,
    CodUser VARCHAR2(30) NOT NULL,
    FechaRegistro TIMESTAMP NOT NULL,
    CodUserUpdate VARCHAR2(30) NOT NULL,
    FechaRegistroUpdate TIMESTAMP NOT NULL,
    CONSTRAINT pk_RefererServidores PRIMARY KEY (IdRefererServidores)
);

CREATE TABLE aire.AppsFileServerPaths (
    ID NUMBER NOT NULL PRIMARY KEY,
    CodAplicaciones NUMBER NOT NULL,
    PathWeb NVARCHAR2(255) NOT NULL,
    PathRed NVARCHAR2(255) NOT NULL,
    PathRedArchivo NVARCHAR2(255) NOT NULL,
    PathWebArchivo NVARCHAR2(255) NOT NULL,
    Observacion VARCHAR2(200),
    Estado CHAR(1) CHECK (Estado IN ('0', '1')) NOT NULL
);

CREATE TABLE aire.PeticionesCors (
    Id_PeticionesCors NUMBER GENERATED BY DEFAULT AS IDENTITY,
    RequestHeadersReferer NVARCHAR2(1000) NOT NULL,
    Token NVARCHAR2(1000),
    Grupo VARCHAR2(100),
    ControllerName VARCHAR2(100),
    ActionMethod VARCHAR2(50),
    MethodType VARCHAR2(50),
    CodUser VARCHAR2(15) NOT NULL,
    FechaRegistro TIMESTAMP NOT NULL,
    CONSTRAINT pk_PeticionesCors PRIMARY KEY (Id_PeticionesCors)
);

CREATE TRIGGER aire.VerificarNewRefererServers
AFTER INSERT ON aire.PeticionesCors
FOR EACH ROW
DECLARE
    vCount NUMBER;
BEGIN
    
    -- Lógica del disparador
    SELECT COUNT(*)
    INTO vCount
    FROM aire.RefererServidores rs
    WHERE rs.RequestHeadersReferer = :NEW.RequestHeadersReferer;

    IF vCount = 0 THEN
        INSERT INTO aire.RefererServidores (
            RequestHeadersReferer,
            PermitirAcceso,
            CodUser,
            FechaRegistro,
            CodUserUpdate,
            FechaRegistroUpdate
        ) VALUES (
            :NEW.RequestHeadersReferer,
            0,
            '7777777',
            SYSTIMESTAMP,
            '7777777',
            SYSTIMESTAMP
        );
    END IF;
END;
/