SET SERVEROUTPUT ON;

SET DEFINE OFF --Ejecutar  primero este comando para evitar q tome el & como variable de sustitucion
MERGE INTO aire.gnl_rutas_archivo_servidor destino
USING (
    select 1 as id_ruta_archivo,1 as id_aplicacion,'https://op360dev.air-e.com:8083/api/Op360Files/GetFiles?id_soporte=' as ruta_web,'/app/scr/files' as ruta_red,'Reservado' as ruta_red_archivo,'pruebas' as ruta_web_archivo,'pruebas'  as observacion,'1' as estado from dual	union all
	select 4 as id_ruta_archivo,1 as id_aplicacion,'https://op360dev.air-e.com:8083/api/Op360Files/GetFiles?id_soporte=' as ruta_web,'/app/scr/files' as ruta_red,'Reservado' as ruta_red_archivo,'Produccion' as ruta_web_archivo,'Exclusivo para el cargue de archivos desde cargue masivo en scr produccion.'  as observacion,'1' as estado from dual	union all
	select 8 as id_ruta_archivo,1 as id_aplicacion,'https://op360dev.air-e.com:8083/api/Op360Files/GetFilesReporte?usuario=YWRtaW5aQzlaZkpFVlhzamRLaVlB&contrasena=MjRzZDc2YXIqKlpDOVpmSkVWWHNqZEtpWUE=&id_soporte=' as ruta_web,'NA' as ruta_red,'Reservado' as ruta_red_archivo,'0' as ruta_web_archivo,'JasperReports: RUTA_WEB provee la ruta web para descargar imagenes y firmas para el reporte acta cierre de ordenes.'  as observacion,'1' as estado from dual	union all
	select 88 as id_ruta_archivo,1 as id_aplicacion,'http://localhost:3186/api/Op360Files/GetFilesReporte?usuario=YWRtaW5aQzlaZkpFVlhzamRLaVlB&contrasena=MjRzZDc2YXIqKlpDOVpmSkVWWHNqZEtpWUE=&id_soporte=' as ruta_web,'NA' as ruta_red,'Reservado' as ruta_red_archivo,'0' as ruta_web_archivo,'JasperReports: RUTA_WEB provee la ruta web para descargar imagenes y firmas para el reporte acta cierre de ordenes en entorno Local.'  as observacion,'1' as estado from dual	union all
	select 9 as id_ruta_archivo,1 as id_aplicacion,'https://10.20.16.122:8080/jri/report?_repName=Op360/report1&_repFormat=pdf&prIdImg=8&prIdOrden=' as ruta_web,'NA' as ruta_red,'Reservado' as ruta_red_archivo,'Produccion' as ruta_web_archivo,'JasperReports: RUTA_WEB url servidor de Jasper el cual genera reporte scr Acta Ordenes'  as observacion,'1' as estado from dual	union all
	select 12 as id_ruta_archivo,1 as id_aplicacion,'NA' as ruta_web,'C:\tmp\Op360Files\ImgMovileScr' as ruta_red,'Reservado' as ruta_red_archivo,'0' as ruta_web_archivo,'Modulo exclusivo para Scr Mobile para sus fotogracias y firmas en Local'  as observacion,'1' as estado from dual	union all
	select 24 as id_ruta_archivo,1 as id_aplicacion,'https://localhost:44326/api/Op360Files/GetFiles?id_soporte=' as ruta_web,'C:\tmp\Op360Files' as ruta_red,'Reservado' as ruta_red_archivo,'Pruebas local' as ruta_web_archivo,'Modulo exclusivo para Gos Mobile para sus fotogracias y firmas en Local.'  as observacion,'1' as estado from dual	union all
	select 99 as id_ruta_archivo,1 as id_aplicacion,'https://10.20.16.122:8080/jri/report?' as ruta_web,'NA' as ruta_red,'Reservado' as ruta_red_archivo,'Produccion' as ruta_web_archivo,'JasperReports: RUTA_WEB url dinamica servidor de Jasper el cual genera reporte scr Acta Ordenes'  as observacion,'1' as estado from dual	union all
	select 3 as id_ruta_archivo,1 as id_aplicacion,'https://localhost:44326/api/Op360Files/GetPlantillaCMBase64?codigo=CRMAO' as ruta_web,'NA' as ruta_red,'Reservado' as ruta_red_archivo,'Pruebas local' as ruta_web_archivo,'Exclusivo para descarga plantilla cargue masivo en local.'  as observacion,'1' as estado from dual	union all
	select 15 as id_ruta_archivo,1 as id_aplicacion,'https://op360dev.air-e.com:8083/api/Op360Files/GetPlantillaCMBase64?codigo=PRSOR' as ruta_web,'NA' as ruta_red,'Reservado' as ruta_red_archivo,'Produccion' as ruta_web_archivo,'Exclusivo para descarga plantilla cargue masivo Reasignacion Contratista en otros ambientes.'  as observacion,'1' as estado from dual	union all
	select 16 as id_ruta_archivo,1 as id_aplicacion,'https://localhost:44326/api/Op360Files/GetPlantillaCMBase64?codigo=PRSOR' as ruta_web,'NA' as ruta_red,'Reservado' as ruta_red_archivo,'Pruebas local' as ruta_web_archivo,'Exclusivo para descarga plantilla cargue masivo Reasignacion Contratista en local.'  as observacion,'1' as estado from dual	union all
	select 17 as id_ruta_archivo,1 as id_aplicacion,'https://op360dev.air-e.com:8083/api/Op360Files/GetPlantillaCMBase64?codigo=PCORD' as ruta_web,'NA' as ruta_red,'Reservado' as ruta_red_archivo,'Produccion' as ruta_web_archivo,'Exclusivo para descarga plantilla cargue masivo Legalizacion en otros ambientes.'  as observacion,'1' as estado from dual	union all
	select 18 as id_ruta_archivo,1 as id_aplicacion,'https://localhost:44326/api/Op360Files/GetPlantillaCMBase64?codigo=PCORD' as ruta_web,'NA' as ruta_red,'Reservado' as ruta_red_archivo,'Pruebas local' as ruta_web_archivo,'Exclusivo para descarga plantilla cargue masivo legalizacion en local.'  as observacion,'1' as estado from dual	union all
	select 100 as id_ruta_archivo,1 as id_aplicacion,'https://op360dev.air-e.com:8083/api/Op360Files/GetPlantillaCMBase64?codigo=PASGT' as ruta_web,'NA' as ruta_red,'Reservado' as ruta_red_archivo,'Produccion' as ruta_web_archivo,'Exclusivo para descarga plantilla cargue masivo Asignacion Tecnico en otros ambientes.'  as observacion,'1' as estado from dual	union all
	select 101 as id_ruta_archivo,1 as id_aplicacion,'https://localhost:44326/api/Op360Files/GetPlantillaCMBase64?codigo=PASGT' as ruta_web,'NA' as ruta_red,'Reservado' as ruta_red_archivo,'Pruebas local' as ruta_web_archivo,'Exclusivo para descarga plantilla cargue masivo Asignacion Tecnico en local.'  as observacion,'1' as estado from dual	union all
	select 102 as id_ruta_archivo,1 as id_aplicacion,'https://op360dev.air-e.com:8083/api/Op360Files/GetPlantillaCMBase64?codigo=PDSGT' as ruta_web,'NA' as ruta_red,'Reservado' as ruta_red_archivo,'Produccion' as ruta_web_archivo,'Exclusivo para descarga plantilla cargue masivo DesAsignacion Tecnico en otros ambientes.'  as observacion,'1' as estado from dual	union all
	select 103 as id_ruta_archivo,1 as id_aplicacion,'https://localhost:44326/api/Op360Files/GetPlantillaCMBase64?codigo=PDSGT' as ruta_web,'NA' as ruta_red,'Reservado' as ruta_red_archivo,'Pruebas local' as ruta_web_archivo,'Exclusivo para descarga plantilla cargue masivo DesAsignacion Tecnico en local.'  as observacion,'1' as estado from dual	union all
	select 2 as id_ruta_archivo,1 as id_aplicacion,'https://op360dev.air-e.com:8083/api/Op360Files/GetFiles?id_soporte=' as ruta_web,'/app/scr/images' as ruta_red,'Reservado' as ruta_red_archivo,'0' as ruta_web_archivo,'Modulo exclusivo para Scr Mobile para sus fotogracias y firmas en Produccion. '  as observacion,'1' as estado from dual	union all
	select 5 as id_ruta_archivo,1 as id_aplicacion,'https://op360dev.air-e.com:8083/api/Op360Files/GetFilesBase64?Id_Ruta=4&id_soporte=' as ruta_web,'NA' as ruta_red,'Reservado' as ruta_red_archivo,'Produccion' as ruta_web_archivo,'solo para consulta desde SP: prc_consultar_archivos_instancia desde produccion'  as observacion,'1' as estado from dual	union all
	select 6 as id_ruta_archivo,1 as id_aplicacion,'https://op360dev.air-e.com:8083/api/Op360Files/GetPlantillaCMBase64?codigo=CRMAO' as ruta_web,'NA' as ruta_red,'Reservado' as ruta_red_archivo,'Produccion' as ruta_web_archivo,'Exclusivo para descarga plantilla cargue masivo en otros ambientes.'  as observacion,'1' as estado from dual	union all
	select 7 as id_ruta_archivo,1 as id_aplicacion,'https://op360dev.air-e.com:8083/api/Op360Files/GetPlantillaReporte?usuario=YWRtaW5aQzlaZkpFVlhzamRLaVlB&contrasena=MjRzZDc2YXIqKlpDOVpmSkVWWHNqZEtpWUE=&codigo=LOG02' as ruta_web,'NA' as ruta_red,'Reservado' as ruta_red_archivo,'0' as ruta_web_archivo,'JasperReports: RUTA_WEB provee la ruta web para descargar logo Air-e.'  as observacion,'1' as estado from dual	union all
	select 13 as id_ruta_archivo,1 as id_aplicacion,'https://op360dev.air-e.com:8083/api/Op360Files/GetFiles?id_soporte=' as ruta_web,'C:\tmp\Op360\GD\images' as ruta_red,'Reservado' as ruta_red_archivo,'0' as ruta_web_archivo,'Modulo exclusivo para GD Mobile para sus fotogracias y firmas en Produccion. '  as observacion,'1' as estado from dual	union all
	select 14 as id_ruta_archivo,1 as id_aplicacion,'https://op360dev.air-e.com:8083/api/Op360Files/GetFiles?id_soporte=' as ruta_web,'C:\tmp\Op360\GD\images' as ruta_red,'Reservado' as ruta_red_archivo,'0' as ruta_web_archivo,'Modulo exclusivo para GD Mobile para sus fotogracias y firmas en Local. '  as observacion,'1' as estado from dual	union all
	select 44 as id_ruta_archivo,1 as id_aplicacion,'https://localhost:44326/api/Op360Files/GetFiles?id_soporte=' as ruta_web,'C:\tmp\Op360Files' as ruta_red,'Reservado' as ruta_red_archivo,'Pruebas local' as ruta_web_archivo,'Exclusivo para el cargue de archivos desde cargue masivo en scr local.'  as observacion,'1' as estado from dual	union all
	select 55 as id_ruta_archivo,1 as id_aplicacion,'https://localhost:44326/api/Op360Files/GetFilesBase64?Id_Ruta=44&id_soporte=' as ruta_web,'NA' as ruta_red,'Reservado' as ruta_red_archivo,'Pruebas local' as ruta_web_archivo,'solo para consulta desde SP: prc_consultar_archivos_instancia desde local'  as observacion,'1' as estado from dual	union all
	select 21 as id_ruta_archivo,1 as id_aplicacion,'https://op360dev.air-e.com:8083/api/Op360Files/GetFiles?id_soporte=' as ruta_web,'/app/gos/images' as ruta_red,'Reservado' as ruta_red_archivo,'Produccion' as ruta_web_archivo,'Modulo exclusivo para Gos Mobile para sus fotogracias y firmas en Produccion.'  as observacion,'1' as estado from dual	union all
	select 22 as id_ruta_archivo,1 as id_aplicacion,'https://op360dev.air-e.com:8083/api/Op360Files/GetFiles?id_soporte=' as ruta_web,'/app/gos/files' as ruta_red,'Reservado' as ruta_red_archivo,'Produccion' as ruta_web_archivo,'Exclusivo para el cargue de archivos desde cargue masivo en gos produccion.'  as observacion,'1' as estado from dual	union all
	select 23 as id_ruta_archivo,1 as id_aplicacion,'https://localhost:44326/api/Op360Files/GetFiles?id_soporte=' as ruta_web,'C:\tmp\Op360Files' as ruta_red,'Reservado' as ruta_red_archivo,'Pruebas local' as ruta_web_archivo,'Exclusivo para el cargue de archivos desde cargue masivo en gos local.'  as observacion,'1' as estado from dual	union all
	select 10 as id_ruta_archivo,1 as id_aplicacion,'https://op360dev.air-e.com:8083/api/Op360Files/GetPlantillaReporte?usuario=YWRtaW5aQzlaZkpFVlhzamRLaVlB&contrasena=MjRzZDc2YXIqKlpDOVpmSkVWWHNqZEtpWUE=&codigo=LOG02' as ruta_web,'NA' as ruta_red,'Reservado' as ruta_red_archivo,'0' as ruta_web_archivo,'Excel: RUTA_WEB provee la ruta web para descargar logo Air-e.'  as observacion,'1' as estado from dual	union all
	select 11 as id_ruta_archivo,1 as id_aplicacion,'https://op360dev.air-e.com:8083/api/Op360Files/GetPlantillaReporte?usuario=YWRtaW5aQzlaZkpFVlhzamRLaVlB&contrasena=MjRzZDc2YXIqKlpDOVpmSkVWWHNqZEtpWUE=&codigo=LOG01' as ruta_web,'NA' as ruta_red,'Reservado' as ruta_red_archivo,'0' as ruta_web_archivo,'Excel: RUTA_WEB provee la ruta web para descargar logo Air-e en local'  as observacion,'1' as estado from dual	

) origen
ON (
    destino.ID_RUTA_ARCHIVO_SERVIDOR = origen.id_ruta_archivo
)
WHEN MATCHED THEN
    UPDATE SET  destino.ID_APLICACION = origen.id_aplicacion,
                    destino.RUTA_WEB = origen.ruta_web,
                    destino.RUTA_RED = origen.ruta_red,
                    destino.RUTA_RED_ARCHIVO = origen.ruta_red_archivo,
                    destino.RUTA_WEB_ARCHIVO = origen.ruta_web_archivo,
                    destino.OBSERVACION = origen.observacion,
                    destino.ESTADO = origen.estado
WHERE destino.ID_APLICACION != origen.id_aplicacion OR destino.RUTA_WEB != origen.ruta_web OR destino.RUTA_RED != origen.ruta_red OR destino.RUTA_RED_ARCHIVO != origen.ruta_red_archivo OR destino.RUTA_WEB_ARCHIVO != origen.ruta_web_archivo OR destino.OBSERVACION != origen.observacion OR destino.ESTADO != origen.estado
WHEN NOT MATCHED THEN
INSERT (ID_RUTA_ARCHIVO_SERVIDOR, ID_APLICACION, RUTA_WEB, RUTA_RED, RUTA_RED_ARCHIVO, RUTA_WEB_ARCHIVO, OBSERVACION, ESTADO)
VALUES (origen.id_ruta_archivo, origen.id_aplicacion, origen.ruta_web, origen.ruta_red, origen.ruta_red_archivo, origen.ruta_web_archivo, origen.observacion, origen.estado);
